apiVersion: v1
kind: Service
metadata:
  name: cloud-step3-service
spec:
  selector:
    app: cloud-step3
  ports:
    - protocol: "TCP"
      port: 6000
      targetPort: 5000
  externalIPs:
    - 192.168.0.10

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-step3
spec:
  selector:
    matchLabels:
      app: cloud-step3
  replicas: 2
  template:
    metadata:
      labels:
        app: cloud-step3
    spec:
      containers:
        - name: cloud-step3
          image: docker.io/amirmraei/cloud-cc2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-step3
data:
  api_to_read: "http://worldtimeapi.org/api/timezone/Europe/Rome"